services:
  backend:
    container_name: culf_backend
    platform: linux/x86_64
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ../backend:/app
    ports:
      - 8000:8000
    env_file:
      - ../backend/.env

  frontend:
    container_name: culf_frontend
    platform: linux/x86_64
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    env_file:
      - ../frontend/.env